export interface Day {
  weekday: string;
  year: number;
  month_name: string;
  month: number;
  day: number;
  holiday: boolean;
  dayOfyear: number;
}
export const calendarArray: Day[] = [
  {
    day: 1,
    dayOfyear: 1,
    holiday: true,
    month: 1,
    month_name: "فروردین",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 2,
    holiday: true,
    month: 1,
    month_name: "فروردین",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 3,
    holiday: true,
    month: 1,
    month_name: "فروردین",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 4,
    holiday: true,
    month: 1,
    month_name: "فروردین",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 5,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 6,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 7,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 8,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 9,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 10,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 11,
    holiday: true,
    month: 1,
    month_name: "فروردین",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 12,
    holiday: true,
    month: 1,
    month_name: "فروردین",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 13,
    holiday: true,
    month: 1,
    month_name: "فروردین",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 14,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 15,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 16,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 17,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 18,
    holiday: true,
    month: 1,
    month_name: "فروردین",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 19,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 20,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 21,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 22,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 23,
    holiday: true,
    month: 1,
    month_name: "فروردین",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 24,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 25,
    holiday: true,
    month: 1,
    month_name: "فروردین",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 26,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 27,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 28,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 29,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 30,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 31,
    dayOfyear: 31,
    holiday: false,
    month: 1,
    month_name: "فروردین",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 32,
    holiday: true,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 33,
    holiday: true,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 34,
    holiday: true,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 35,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 36,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 37,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 38,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 39,
    holiday: true,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 40,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 41,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 42,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 43,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 44,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 45,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 46,
    holiday: true,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 47,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 48,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 49,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 50,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 51,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 52,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 53,
    holiday: true,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 54,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 55,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 56,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 57,
    holiday: true,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 58,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 59,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 60,
    holiday: true,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 61,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 31,
    dayOfyear: 62,
    holiday: false,
    month: 2,
    month_name: "اردیبهشت",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 63,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 64,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 65,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 66,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 67,
    holiday: true,
    month: 3,
    month_name: "خرداد",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 68,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 69,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 70,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 71,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 72,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 73,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 74,
    holiday: true,
    month: 3,
    month_name: "خرداد",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 75,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 76,
    holiday: true,
    month: 3,
    month_name: "خرداد",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 77,
    holiday: true,
    month: 3,
    month_name: "خرداد",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 78,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 79,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 80,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 81,
    holiday: true,
    month: 3,
    month_name: "خرداد",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 82,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 83,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 84,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 85,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 86,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 87,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 88,
    holiday: true,
    month: 3,
    month_name: "خرداد",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 89,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 90,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 91,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 92,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 31,
    dayOfyear: 93,
    holiday: false,
    month: 3,
    month_name: "خرداد",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 94,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 95,
    holiday: true,
    month: 4,
    month_name: "تیر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 96,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 97,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 98,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 99,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 100,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 101,
    holiday: true,
    month: 4,
    month_name: "تیر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 102,
    holiday: true,
    month: 4,
    month_name: "تیر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 103,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 104,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 105,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 106,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 107,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 108,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 109,
    holiday: true,
    month: 4,
    month_name: "تیر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 110,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 111,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 112,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 113,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 114,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 115,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 116,
    holiday: true,
    month: 4,
    month_name: "تیر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 117,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 118,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 119,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 120,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 121,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 122,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 123,
    holiday: true,
    month: 4,
    month_name: "تیر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 31,
    dayOfyear: 124,
    holiday: false,
    month: 4,
    month_name: "تیر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 125,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 126,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 127,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 128,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 129,
    holiday: true,
    month: 5,
    month_name: "مرداد",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 130,
    holiday: true,
    month: 5,
    month_name: "مرداد",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 131,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 132,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 133,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 134,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 135,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 136,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 137,
    holiday: true,
    month: 5,
    month_name: "مرداد",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 138,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 139,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 140,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 141,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 142,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 143,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 144,
    holiday: true,
    month: 5,
    month_name: "مرداد",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 145,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 146,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 147,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 148,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 149,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 150,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 151,
    holiday: true,
    month: 5,
    month_name: "مرداد",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 152,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 153,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 154,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 31,
    dayOfyear: 155,
    holiday: false,
    month: 5,
    month_name: "مرداد",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 156,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 157,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 158,
    holiday: true,
    month: 6,
    month_name: "شهریور",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 159,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 160,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 161,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 162,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 163,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 164,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 165,
    holiday: true,
    month: 6,
    month_name: "شهریور",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 166,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 167,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 168,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 169,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 170,
    holiday: true,
    month: 6,
    month_name: "شهریور",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 171,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 172,
    holiday: true,
    month: 6,
    month_name: "شهریور",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 173,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 174,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 175,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 176,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 177,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 178,
    holiday: true,
    month: 6,
    month_name: "شهریور",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 179,
    holiday: true,
    month: 6,
    month_name: "شهریور",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 180,
    holiday: true,
    month: 6,
    month_name: "شهریور",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 181,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 182,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 183,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 184,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 185,
    holiday: false,
    month: 6,
    month_name: "شهریور",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 31,
    dayOfyear: 186,
    holiday: true,
    month: 6,
    month_name: "شهریور",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 187,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 188,
    holiday: true,
    month: 7,
    month_name: "مهر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 189,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 190,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 191,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 192,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 193,
    holiday: true,
    month: 7,
    month_name: "مهر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 194,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 195,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 196,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 197,
    holiday: true,
    month: 7,
    month_name: "مهر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 198,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 199,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 200,
    holiday: true,
    month: 7,
    month_name: "مهر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 201,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 202,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 203,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 204,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 205,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 206,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 207,
    holiday: true,
    month: 7,
    month_name: "مهر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 208,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 209,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 210,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 211,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 212,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 213,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 214,
    holiday: true,
    month: 7,
    month_name: "مهر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 215,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 216,
    holiday: false,
    month: 7,
    month_name: "مهر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 217,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 218,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 219,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 220,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 221,
    holiday: true,
    month: 8,
    month_name: "آبان",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 222,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 223,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 224,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 225,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 226,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 227,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 228,
    holiday: true,
    month: 8,
    month_name: "آبان",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 229,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 230,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 231,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 232,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 233,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 234,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 235,
    holiday: true,
    month: 8,
    month_name: "آبان",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 236,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 237,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 238,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 239,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 240,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 241,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 242,
    holiday: true,
    month: 8,
    month_name: "آبان",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 243,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 244,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 245,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 246,
    holiday: false,
    month: 8,
    month_name: "آبان",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 247,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 248,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 249,
    holiday: true,
    month: 9,
    month_name: "آذر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 250,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 251,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 252,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 253,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 254,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 255,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 256,
    holiday: true,
    month: 9,
    month_name: "آذر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 257,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 258,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 259,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 260,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 261,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 262,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 263,
    holiday: true,
    month: 9,
    month_name: "آذر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 264,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 265,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 266,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 267,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 268,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 269,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 270,
    holiday: true,
    month: 9,
    month_name: "آذر",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 271,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 272,
    holiday: true,
    month: 9,
    month_name: "آذر",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 273,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 274,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 275,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 276,
    holiday: false,
    month: 9,
    month_name: "آذر",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 277,
    holiday: true,
    month: 10,
    month_name: "دی",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 278,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 279,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 280,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 281,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 282,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 283,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 284,
    holiday: true,
    month: 10,
    month_name: "دی",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 285,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 286,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 287,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 288,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 289,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 290,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 291,
    holiday: true,
    month: 10,
    month_name: "دی",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 292,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 293,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 294,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 295,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 296,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 297,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 298,
    holiday: true,
    month: 10,
    month_name: "دی",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 299,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 300,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 301,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 302,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 303,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 304,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 305,
    holiday: true,
    month: 10,
    month_name: "دی",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 306,
    holiday: false,
    month: 10,
    month_name: "دی",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 307,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 308,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 309,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 310,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 311,
    holiday: true,
    month: 11,
    month_name: "بهمن",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 312,
    holiday: true,
    month: 11,
    month_name: "بهمن",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 313,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 314,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 315,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 316,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 317,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 318,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 319,
    holiday: true,
    month: 11,
    month_name: "بهمن",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 320,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 321,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 322,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 323,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 324,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 325,
    holiday: true,
    month: 11,
    month_name: "بهمن",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 326,
    holiday: true,
    month: 11,
    month_name: "بهمن",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 327,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 328,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 329,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 330,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 331,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 332,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 333,
    holiday: true,
    month: 11,
    month_name: "بهمن",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 334,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 335,
    holiday: true,
    month: 11,
    month_name: "بهمن",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 30,
    dayOfyear: 336,
    holiday: false,
    month: 11,
    month_name: "بهمن",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 1,
    dayOfyear: 337,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 2,
    dayOfyear: 338,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 3,
    dayOfyear: 339,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 4,
    dayOfyear: 340,
    holiday: true,
    month: 12,
    month_name: "اسفند",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 5,
    dayOfyear: 341,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 6,
    dayOfyear: 342,
    holiday: true,
    month: 12,
    month_name: "اسفند",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 7,
    dayOfyear: 343,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 8,
    dayOfyear: 344,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 9,
    dayOfyear: 345,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 10,
    dayOfyear: 346,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 11,
    dayOfyear: 347,
    holiday: true,
    month: 12,
    month_name: "اسفند",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 12,
    dayOfyear: 348,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 13,
    dayOfyear: 349,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 14,
    dayOfyear: 350,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 15,
    dayOfyear: 351,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 16,
    dayOfyear: 352,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 17,
    dayOfyear: 353,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 18,
    dayOfyear: 354,
    holiday: true,
    month: 12,
    month_name: "اسفند",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 19,
    dayOfyear: 355,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 20,
    dayOfyear: 356,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 21,
    dayOfyear: 357,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 22,
    dayOfyear: 358,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "سه شنبه",
    year: 1402,
  },
  {
    day: 23,
    dayOfyear: 359,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "چهارشنبه",
    year: 1402,
  },
  {
    day: 24,
    dayOfyear: 360,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "پنجشنبه",
    year: 1402,
  },
  {
    day: 25,
    dayOfyear: 361,
    holiday: true,
    month: 12,
    month_name: "اسفند",
    weekday: "جمعه",
    year: 1402,
  },
  {
    day: 26,
    dayOfyear: 362,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "شنبه",
    year: 1402,
  },
  {
    day: 27,
    dayOfyear: 363,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "یکشنبه",
    year: 1402,
  },
  {
    day: 28,
    dayOfyear: 364,
    holiday: false,
    month: 12,
    month_name: "اسفند",
    weekday: "دوشنبه",
    year: 1402,
  },
  {
    day: 29,
    dayOfyear: 365,
    holiday: true,
    month: 12,
    month_name: "اسفند",
    weekday: "سه شنبه",
    year: 1402,
  },
];

const calendarGenerator = () => {
  const weekDays = [
    "شنبه",
    "یکشنبه",
    "دوشنبه",
    "سه شنبه",
    "چهارشنبه",
    "پنجشنبه",
    "جمعه",
  ];
  let weekDaySelector = 2; // سه شنبه
  const months = [
    "فروردین",
    "اردیبهشت",
    "خرداد",
    "تیر",
    "مرداد",
    "شهریور",
    "مهر",
    "آبان",
    "آذر",
    "دی",
    "بهمن",
    "اسفند",
  ];
  const daysOfMonth = [31, 31, 31, 31, 31, 31, 30, 30, 30, 30, 30, 29];
  const holidays = [
    [1, 2, 3, 4, 12, 13, 23],
    [2, 3, 26],
    [14, 15],
    [8, 16],
    [5, 6],
    [15, 23, 25],
    [2, 11],
    [0],
    [26],
    [0],
    [5, 19, 29],
    [6, 29],
  ];
  const calender = daysOfMonth.map((month) => {});
  let dayOfYear = 1;
  let date: Day[] = [];
  for (let i = 0; i < daysOfMonth.length; i++) {
    for (let j = 0; j < daysOfMonth[i]; j++) {
      weekDaySelector++;
      if (weekDaySelector === 7) {
        weekDaySelector = 0;
      }
      let boool = holidays[i].find((holiday) => holiday === j + 1);
      if (weekDaySelector === 6) {
        boool = 1;
      }
      date.push({
        day: j + 1,
        dayOfyear: dayOfYear++,
        holiday: !!boool,
        month: i + 1,
        month_name: months[i],
        weekday: weekDays[weekDaySelector],
        year: 1402,
      });
    }
  }
  console.log(date);
  return date;
};

function convertFaToEnDigits(faDigits: string): number {
  let enDigits = "";
  for (const digit of faDigits) {
    switch (digit) {
      case "۰":
        enDigits += "0";
        break;
      case "۱":
        enDigits += "1";
        break;
      case "۲":
        enDigits += "2";
        break;
      case "۳":
        enDigits += "3";
        break;
      case "۴":
        enDigits += "4";
        break;
      case "۵":
        enDigits += "5";
        break;
      case "۶":
        enDigits += "6";
        break;
      case "۷":
        enDigits += "7";
        break;
      case "۸":
        enDigits += "8";
        break;
      case "۹":
        enDigits += "9";
        break;
      default:
        enDigits += digit;
    }
  }
  return parseInt(enDigits);
}

export const getdayOfYear = (): number => {
  let date = new Date().toLocaleDateString("fa-IR");
  const splited = date.split("/");
  const month = convertFaToEnDigits(splited[1]);
  const day = convertFaToEnDigits(splited[2]);
  if (month < 8) {
    return (month - 1) * 31 + day;
  }
  if (month >= 8) {
    const temp = month - 7;
    return temp * 30 + 186 + day;
  } else {
    return 0;
  }
};

export const jalali_to_gregorian = (date: string) => {
  const splitDate = date.split("/");

  const JalaliDate = {
    g_days_in_month: [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31],
    j_days_in_month: [31, 31, 31, 31, 31, 31, 30, 30, 30, 30, 30, 29],
  };
  const j_y = parseInt(splitDate[0]);
  const j_m = parseInt(splitDate[1]);
  const j_d = parseInt(splitDate[2]);

  const jy = j_y - 979;
  const jm = j_m - 1;
  const jd = j_d - 1;

  let j_day_no =
    365 * jy + Math.trunc(jy / 33) * 8 + Math.trunc(((jy % 33) + 3) / 4);
  for (let i = 0; i < jm; ++i) j_day_no += JalaliDate.j_days_in_month[i];

  j_day_no += jd;

  let g_day_no = j_day_no + 79;

  let gy =
    1600 +
    400 *
      Math.trunc(
        g_day_no / 146097
      ); /* 146097 = 365*400 + 400/4 - 400/100 + 400/400 */
  g_day_no = g_day_no % 146097;

  let leap = true;
  if (g_day_no >= 36525) {
    /* 36525 = 365*100 + 100/4 */
    g_day_no--;
    gy +=
      100 *
      Math.trunc(g_day_no / 36524); /* 36524 = 365*100 + 100/4 - 100/100 */
    g_day_no = g_day_no % 36524;

    if (g_day_no >= 365) g_day_no++;
    else leap = false;
  }

  gy += 4 * Math.trunc(g_day_no / 1461); /* 1461 = 365*4 + 4/4 */
  g_day_no %= 1461;

  if (g_day_no >= 366) {
    leap = false;

    g_day_no--;
    gy += Math.trunc(g_day_no / 365);
    g_day_no = g_day_no % 365;
  }

  for (
    var i = 0;
    g_day_no >= JalaliDate.g_days_in_month[i] + (i == 1 && leap ? 1 : 0);
    i++
  ) {
    g_day_no -= JalaliDate.g_days_in_month[i] + (i == 1 && leap ? 1 : 0);
  }
  let gm = i + 1;
  let gd = g_day_no + 1;
  return `${gy}/${gm}/${gd}`;
};
